### ISSUE TITLE
Nothing ending up in log file

### ISSUE THREAD

**Issue by landmanbester** [gijzelaerr/pyscilog#1]
Not sure if I am doing this right but there was definitely an issue with with the file handler. I changed state['file_handler'] to state['_file_handler']. It now runs and produces a log file with the desired name but nothing gets written to it. Is it supposed to as simple as setting?
```
pyscilog.log_to_file('filename.log')
```

**Comment by gijzelaerr** [comment]
I didn't get to testing the code really after the refactor, so yeah there might be a thing or two still wrong.

Idea was that the API, although cleaned up and made pep8 compliant, should be the same.

**Comment by landmanbester** [comment]
Ah wait, it doesn't end up in the log file if I don't initialise the the logger object at the top of the python file. Seems to be working if I do
